repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: autoflake
        name: Remove unused imports
        entry: bash -c 'autoflake "$@"'
        language: python
        args: ["--imports=django", "--ignore-init-module-imports", "--in-place"]
        files: \.py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
