# Generated by Django 4.0.1 on 2022-02-12 21:03
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def save_compositions(apps, schema_editor):
    Composition = apps.get_model("web", "Composition")

    logger.info(f"Re-saving {Composition.objects.count()} compositions")
    for c in Composition.objects.all():
        c.save()
    logger.info("Finished data migration!")


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            save_compositions,
        )
    ]
