# Generated by Django 4.0.1 on 2022-02-12 21:03
import logging

from django.db import migrations

from choralcat.core.utils import timer

logger = logging.getLogger(__name__)


@timer
def save_compositions(apps, schema_editor):
    Composition = apps.get_model("web", "Composition")
    logger.info(f"Re-saving {Composition.objects.count()} compositions")
    for c in Composition.objects.all():
        c.save()
    logger.info("Finished data migration!")


class Migration(migrations.Migration):

    dependencies = [("web", "0005_composition_title_unidecode")]
    operations = [
        migrations.RunPython(save_compositions),
    ]
