# Generated by Django 4.0.1 on 2022-02-12 22:04
import logging

from django.db import migrations

from choralcat.core.utils import timer

logger = logging.getLogger(__name__)


@timer
def save_all_people(apps, schema_editor):
    Person = apps.get_model("web", "Person")
    for p in Person.objects.all():
        p.slug = ""
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("data_migrations", "0001_initial"),
        ("web", "0006_alter_person_slug"),
    ]

    operations = [
        migrations.RunPython(save_all_people),
    ]
