# Generated by Django 4.0.1 on 2022-04-30 01:45
import logging

from django.db import migrations

from choralcat.core.utils import timer

logger = logging.getLogger(__name__)

models = [
    "UserProfile",
    "Person",
    "Category",
    "Instrument",
    "Topic",
    "Tag",
    "Composition",
    "Program",
]


@timer
def _add_chanticleer_to_all(apps, schema_editor):
    org_model = apps.get_model("web", "Organization")
    chanticleer, created = org_model.objects.get_or_create(name="Chanticleer")
    if created:
        logger.info(f"Created new chanticleer object {chanticleer.pk}")
    else:
        logger.info(f"Found chanticleer object {chanticleer.pk}")

    for model_name in models:
        model = apps.get_model("web", model_name)
        num_updated = model.objects.update(organization=chanticleer)
        logger.info(f"Updated {num_updated} {model_name}")
    logger.info("Migration done!")


class Migration(migrations.Migration):

    dependencies = [
        ("data_migrations", "0002_FirstNameLastNameSlug"),
        ("web", "0007_organization_category_organization_and_more"),
    ]

    operations = [
        migrations.RunPython(_add_chanticleer_to_all),
    ]
