# Generated by Django 4.0.1 on 2022-01-23 17:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import choralcat.core.fields


class Migration(migrations.Migration):

    replaces = [
        ("web", "0001_initial"),
        ("web", "0002_composition_title_slug_person_name_slug_and_more"),
        ("web", "0003_tag_composition_tags"),
        ("web", "0004_alter_composition_accompaniment_and_more"),
        ("web", "0005_remove_composition_voicing_composition_voicing"),
        ("web", "0006_delete_voice"),
        ("web", "0007_alter_category_options_alter_program_ordering"),
        ("web", "0008_person_non_male_identifying_person_poc_topic_and_more"),
        ("web", "0009_alter_instrument_options_alter_topic_options_and_more"),
        ("web", "0010_alter_person_options"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name_plural": "Categories",
            },
            bases=(
                models.Model,
                choralcat.core.models.TimeStampMixin,
                choralcat.core.models.CreatedByMixin,
            ),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(blank=True, max_length=256)),
                ("birth", models.DateField(blank=True, null=True)),
                ("death", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slug",
                    choralcat.core.fields.AutoSlugField(
                        blank=True, null=True, populated_from="first_name", unique=True
                    ),
                ),
                ("non_male_identifying", models.BooleanField(default=False)),
                ("poc", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name_plural": "People",
            },
            bases=(
                models.Model,
                choralcat.core.models.TimeStampMixin,
                choralcat.core.models.CreatedByMixin,
            ),
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ["value", "user"],
            },
            bases=(
                models.Model,
                choralcat.core.models.TimeStampMixin,
                choralcat.core.models.CreatedByMixin,
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "value")},
            },
            bases=(
                models.Model,
                choralcat.core.models.TimeStampMixin,
                choralcat.core.models.CreatedByMixin,
            ),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ["value", "user"],
            },
            bases=(
                models.Model,
                choralcat.core.models.TimeStampMixin,
                choralcat.core.models.CreatedByMixin,
            ),
        ),
        migrations.CreateModel(
            name="Composition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("starting_key", models.CharField(blank=True, max_length=256)),
                ("ending_key", models.CharField(blank=True, max_length=256)),
                ("time_period", models.CharField(blank=True, max_length=256)),
                ("language", models.CharField(blank=True, max_length=256)),
                (
                    "number_of_voices",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("score_link", models.CharField(blank=True, max_length=256)),
                ("notes", models.TextField(blank=True)),
                ("edition_notes", models.TextField(blank=True)),
                (
                    "accompaniment",
                    models.ManyToManyField(blank=True, to="web.Instrument"),
                ),
                (
                    "arrangers",
                    models.ManyToManyField(
                        blank=True, related_name="arrangers", to="web.Person"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="web.Category"),
                ),
                (
                    "composers",
                    models.ManyToManyField(
                        blank=True, related_name="composers", to="web.Person"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slug",
                    choralcat.core.fields.AutoSlugField(
                        blank=True, null=True, populated_from="title", unique=True
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="web.Tag")),
                ("voicing", models.CharField(blank=True, max_length=256)),
                (
                    "topics",
                    models.ManyToManyField(blank=True, to="web.Topic"),
                ),
            ],
            options={
                "ordering": ["title"],
            },
            bases=(
                models.Model,
                choralcat.core.models.TimeStampMixin,
                choralcat.core.models.CreatedByMixin,
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("ordering", models.JSONField(blank=True, default=dict)),
                ("season", models.CharField(blank=True, max_length=256)),
                (
                    "compositions",
                    models.ManyToManyField(blank=True, to="web.Composition"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slug",
                    choralcat.core.fields.AutoSlugField(
                        blank=True, null=True, populated_from="title", unique=True
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(blank=True, to="web.Topic"),
                ),
            ],
            options={
                "ordering": ["season", "title"],
            },
            bases=(
                models.Model,
                choralcat.core.models.TimeStampMixin,
                choralcat.core.models.CreatedByMixin,
            ),
        ),
    ]
