# Generated by Django 4.0.1 on 2022-02-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="nationality",
            field=models.TextField(blank=True),
        ),
    ]
