# Generated by Django 4.0.1 on 2022-04-30 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_alter_person_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="category",
            name="organization",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="web.organization"),
        ),
        migrations.AddField(
            model_name="composition",
            name="organization",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="web.organization"),
        ),
        migrations.AddField(
            model_name="instrument",
            name="organization",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="web.organization"),
        ),
        migrations.AddField(
            model_name="person",
            name="organization",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="web.organization"),
        ),
        migrations.AddField(
            model_name="program",
            name="organization",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="web.organization"),
        ),
        migrations.AddField(
            model_name="tag",
            name="organization",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="web.organization"),
        ),
        migrations.AddField(
            model_name="topic",
            name="organization",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="web.organization"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="organization",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.organization"),
        ),
    ]
