# Generated by Django 4.0.1 on 2022-04-30 02:45

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0007_organization_category_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CCUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="instrument",
            options={"ordering": ["value", "organization"]},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["value", "organization"]},
        ),
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
        migrations.RemoveField(
            model_name="composition",
            name="user",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="user",
        ),
        migrations.RemoveField(
            model_name="person",
            name="user",
        ),
        migrations.RemoveField(
            model_name="program",
            name="user",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="user",
        ),
        migrations.AddField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_creator_related",
                related_query_name="%(app_label)s_%(class)ss_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updater_related",
                related_query_name="%(app_label)s_%(class)ss_updater",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("organization", "value")},
        ),
        migrations.RemoveField(
            model_name="tag",
            name="user",
        ),
    ]
