# Generated by Django 4.0.1 on 2022-05-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_ccuser_alter_instrument_options_alter_topic_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompositionScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="")),
                ("name", models.CharField(max_length=256)),
                (
                    "composition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_attachment",
                        to="web.composition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompositionAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="")),
                ("name", models.CharField(max_length=256)),
                ("composition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.composition")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
