# Generated by Django 4.0.1 on 2022-05-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_compositionscore_compositionattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compositionattachment",
            name="composition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="web.composition"
            ),
        ),
    ]
