# Generated by Django 4.0.1 on 2022-05-01 18:05

import django.db.models.deletion
from django.db import migrations, models

import choralcat.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_alter_compositionattachment_composition"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=choralcat.core.fields.AutoSlugField(blank=True, null=True, populated_from="name", unique=True),
        ),
        migrations.AlterField(
            model_name="compositionattachment",
            name="composition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attachment", to="web.composition"
            ),
        ),
    ]
