# Generated by Django 4.0.1 on 2022-01-22 18:03

import choralcat_core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, choralcat_core.models.TimeStampMixin, choralcat_core.models.CreatedByMixin),
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('starting_key', models.CharField(blank=True, max_length=256)),
                ('ending_key', models.CharField(blank=True, max_length=256)),
                ('time_period', models.CharField(blank=True, max_length=256)),
                ('language', models.CharField(blank=True, max_length=256)),
                ('number_of_voices', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_link', models.CharField(blank=True, max_length=256)),
                ('notes', models.TextField(blank=True)),
                ('edition_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
            bases=(models.Model, choralcat_core.models.TimeStampMixin, choralcat_core.models.CreatedByMixin),
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, choralcat_core.models.TimeStampMixin, choralcat_core.models.CreatedByMixin),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('ordering', models.JSONField(blank=True)),
                ('season', models.CharField(blank=True, max_length=256)),
                ('compositions', models.ManyToManyField(to='choralcat_web.Composition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['season', 'title'],
            },
            bases=(models.Model, choralcat_core.models.TimeStampMixin, choralcat_core.models.CreatedByMixin),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('birth', models.DateField(blank=True, null=True)),
                ('death', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
            bases=(models.Model, choralcat_core.models.TimeStampMixin, choralcat_core.models.CreatedByMixin),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, choralcat_core.models.TimeStampMixin, choralcat_core.models.CreatedByMixin),
        ),
        migrations.AddField(
            model_name='composition',
            name='accompaniment',
            field=models.ManyToManyField(to='choralcat_web.Instrument'),
        ),
        migrations.AddField(
            model_name='composition',
            name='arrangers',
            field=models.ManyToManyField(related_name='arrangers', to='choralcat_web.Person'),
        ),
        migrations.AddField(
            model_name='composition',
            name='categories',
            field=models.ManyToManyField(to='choralcat_web.Category'),
        ),
        migrations.AddField(
            model_name='composition',
            name='composers',
            field=models.ManyToManyField(related_name='composers', to='choralcat_web.Person'),
        ),
        migrations.AddField(
            model_name='composition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='composition',
            name='voicing',
            field=models.ManyToManyField(to='choralcat_web.Voice'),
        ),
    ]
