# Generated by Django 4.0.1 on 2022-01-22 18:05

import choralcat_core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choralcat_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='title_slug',
            field=choralcat_core.fields.AutoSlugField(blank=True, null=True, populated_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_slug',
            field=choralcat_core.fields.AutoSlugField(blank=True, null=True, populated_from='first_name', unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='title_slug',
            field=choralcat_core.fields.AutoSlugField(blank=True, null=True, populated_from='title', unique=True),
        ),
    ]
