# Generated by Django 4.0.1 on 2022-01-22 18:08

import choralcat_core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('choralcat_web', '0002_composition_title_slug_person_name_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'value')},
            },
            bases=(models.Model, choralcat_core.models.TimeStampMixin, choralcat_core.models.CreatedByMixin),
        ),
        migrations.AddField(
            model_name='composition',
            name='tags',
            field=models.ManyToManyField(to='choralcat_web.Tag'),
        ),
    ]
