# Generated by Django 4.0.1 on 2022-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choralcat_web', '0003_tag_composition_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='accompaniment',
            field=models.ManyToManyField(blank=True, to='choralcat_web.Instrument'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='arrangers',
            field=models.ManyToManyField(blank=True, related_name='arrangers', to='choralcat_web.Person'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='categories',
            field=models.ManyToManyField(blank=True, to='choralcat_web.Category'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='composers',
            field=models.ManyToManyField(blank=True, related_name='composers', to='choralcat_web.Person'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='tags',
            field=models.ManyToManyField(blank=True, to='choralcat_web.Tag'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='voicing',
            field=models.ManyToManyField(blank=True, to='choralcat_web.Voice'),
        ),
        migrations.AlterField(
            model_name='program',
            name='compositions',
            field=models.ManyToManyField(blank=True, to='choralcat_web.Composition'),
        ),
    ]
