# Generated by Django 4.0.1 on 2022-01-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choralcat_web', '0004_alter_composition_accompaniment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='voicing',
        ),
        migrations.AddField(
            model_name='composition',
            name='voicing',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
