# Generated by Django 4.0.1 on 2022-01-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choralcat_web', '0005_remove_composition_voicing_composition_voicing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voice',
        ),
    ]
