# Generated by Django 4.0.1 on 2022-01-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choralcat_web', '0006_delete_voice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='program',
            name='ordering',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
