name: deploy
on:
  workflow_run:
    workflows: ["test"]
    branches: ["master"]
    types: [completed]
env:
  DEBUG: 'True'
jobs:
  deploy:
    concurrency: deploy-prod
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Download static files
        uses: actions/download-artifact@v2
        with:
          name: staticfiles
      - name: Transfer static files
        run: scp staticfiles.tar ${{secrets.SSH_USER}}@${{ secrets.SSH_HOST }}:/apps/choralcat
      # The following step must be commented out when setting up the CI/CD in order
      # to bootstrap the process, since the initial repo might not have the deploy
      # script.
      - name: Run deploy script on host
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /apps/choralcat/deploy.sh ${{ github.sha }}
      - run: echo '🥳 Deploy complete!'
