name: test
on: [push]
env:
  DEBUG: 'True'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - name: Install dependencies
        run: make install
      - name: Build static files
        run: make build
      - name: Run tests
        run: make test
      - name: Bundle static files
        run: tar -cvf staticfiles.tar staticfiles/
      - name: Store static files
        uses: actions/upload-artifact@v2
        with:
          name: staticfiles
          path: staticfiles.tar
